INSERT INTO customer
VALUES(1, 'Hermione Granger');
INSERT INTO customer
VALUES(2, 'Ericka Cespedes');
INSERT INTO customer
VALUES(3, 'Charlie Jimenez');
INSERT INTO customer
VALUES(4, 'Sara Castro');
INSERT INTO customer
VALUES(5, 'Gloriana Salazar');
INSERT INTO customer
VALUES(6, 'Mariela Araya');
INSERT INTO customer
VALUES(7, 'Eduardo Munoz');
INSERT INTO customer
VALUES(8, 'Carlos Salazar');
INSERT INTO customer
VALUES(9, 'Paula Moya');
INSERT INTO customer
VALUES(10, 'Mauricio Cespedes');
INSERT INTO customer
VALUES(11, 'Carlos Cespedes');
INSERT INTO customer
VALUES(12, 'David Martinez');
INSERT INTO customer
VALUES(13, 'Benedict Cumberbatch');
INSERT INTO customer
VALUES(14, 'Lucia Morales');
INSERT INTO customer
VALUES(15, 'Sofia Molina');
